[[repos]]
url = "https://github.com/hastagaming/acp"
app_slug = "acp"
branch = "acp-downloads"
visibility = "public"
module_path = ""
build_system = "auto"
version = ""

[[repos]]
url = "https://github.com/hastagaming/brewer"
app_slug = "brewer"
branch = "brewer-downloads"
visibility = "public"
module_path = ""
build_system = "auto"
version = ""