# only examples

[[repos]]
url = "https://github.com/hastagaming/acp"
repo = "acp"
app_slug = "acp"
branch = "acp-downloads"
visibility = "public"

# this too
[[repos]]
owner = "hastagaming"
repo = "brewer"
app_slug = "brewer"
branch = "brewer-downloads"
visibility = "public"